### ISSUE TITLE
Question: Is anyone successfully using this with Azure AD's passwordless login?

### ISSUE THREAD

**Issue by lorenlang** [24Slides/laravel-saml2#93]
I've been using this package for a while now for a pretty standard username/password login to our enterprise SSO. But our network team (keepers of the Azure) are telling me that the SSO request that's coming from my app is by default requiring that a password be entered. 
* Does the package support auth requests that accept passwordless entry?
* If so, is there a setting that I'm missing somewhere?

**Comment by skydudie** [comment]
Hi @lorenlang,

I think it might be related to the `requestedAuthnContext` that you specify in `config/saml2.php`

In order to get passkeys to work for us we had to disable sending the `requestedAuthnContext` by setting the config to `'requestedAuthnContext' => false`

This allowed Azure to authenticate our users through other means besides usernames and passwords.

**Comment by lorenlang** [comment]
@skydudie  That worked perfectly. Thanks so much!
